suppressed_signatures:
- signature_id: 2210054
  note: "Added via Alert Detail UI at 2026-04-24T13:18:04Z \u2014 STREAM excessive\
    \ retransmissions"
- signature_id: 2210050
  note: "Added via Alert Detail UI at 2026-04-24T13:18:04Z \u2014 STREAM reassembly\
    \ overlap"
- signature_id: 2017928
  note: "Added via Alert Detail UI at 2026-04-24T13:18:04Z \u2014 ET INFO torproject\
    \ lookup"
