"""Generate forensic evidence packages for law enforcement transmission.

Creates a self-contained ZIP archive with all evidence, context,
and documentation needed for a formal complaint or forensic analysis.

SECURITY:
- NEVER include API keys, passwords, tokens, or secrets
- All config values matching key/secret/password/token are redacted
- All timestamps in UTC (ISO 8601)
- SHA-256 checksums for every file (chain of evidence integrity)
"""

from __future__ import annotations

import hashlib
import json
import logging
import shutil
import tempfile
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from src.models import DecisionRecord

logger = logging.getLogger("ward_soar.forensic_report")

SENSITIVE_KEY_PATTERNS = ("key", "secret", "password", "token")

README_TEMPLATE = """\
================================================================================
  FORENSIC REPORT — NETWORK SECURITY INCIDENT
================================================================================

Generation date    : {generation_date}
Generated by       : WardSOAR v{version} — Loic Ader (loicata.com)
Alert identifier   : {record_id}

================================================================================
  INCIDENT SUMMARY
================================================================================

Detection date and time : {alert_timestamp}
Source IP (attacker)    : {src_ip}
Source port             : {src_port}
Destination IP (target) : {dest_ip}
Destination port        : {dest_port}
Protocol                : {protocol}

Detection signature : {signature}
Signature ID        : SID {signature_id}
Category            : {category}
Suricata severity   : {severity}

================================================================================
  VERDICT AND ACTIONS
================================================================================

Analysis verdict    : {verdict}
Confidence level    : {confidence}
Reasoning           : {reasoning}

Actions taken:
{actions_taken}

================================================================================
  ARCHIVE CONTENTS
================================================================================

  01_suricata_alert/          — Original IDS alert and related alerts
  02_network_context/         — Network state at the time of the alert
  03_local_forensic_analysis/ — Host analysis (processes, Sysmon, registry)
  04_virustotal_analysis/     — VirusTotal lookup results
  05_ai_analysis/             — Artificial intelligence threat analyses
  06_actions_taken/           — Details of blocking actions executed
  07_system_configuration/    — Detection system configuration

All timestamps are in UTC (ISO 8601 format).
All files are UTF-8 encoded.
SHA-256 checksums for each file are listed in CHECKSUMS.sha256.

================================================================================
  CONTACT
================================================================================

System administrator : {contact}
Detection tool       : WardSOAR — Loic Ader (loicata.com)

================================================================================
"""


class ForensicReportGenerator:
    """Generate forensic evidence ZIP packages for law enforcement.

    Args:
        config: ForensicReport configuration dict from config.yaml.
    """

    def __init__(self, config: dict[str, Any]) -> None:
        self._version: str = config.get("app_version", "0.1.0")
        self._contact: str = config.get("contact", "loicata.com")
        self._temp_dir: str = config.get("temp_dir", tempfile.gettempdir())
        self._include_suspect_files: bool = config.get("include_suspect_files", False)
        self._max_suspect_files_size: int = config.get("max_suspect_files_size", 104857600)

    def generate(self, record: DecisionRecord) -> Path:
        """Generate a complete forensic evidence ZIP from a decision record.

        Args:
            record: The complete decision record with all context.

        Returns:
            Path to the generated temporary ZIP file.

        Raises:
            ValueError: If the record has no confirmed threat or no actions taken.
        """
        if record.analysis is None:
            raise ValueError("Cannot generate forensic report: no analysis result")
        if not record.actions_taken:
            raise ValueError("Cannot generate forensic report: no actions taken")

        # Create temp directory for evidence
        report_name = (
            f"FORENSIC_REPORT_{record.alert.src_ip}_" f"{record.timestamp.strftime('%Y-%m-%d')}"
        )
        evidence_dir = Path(self._temp_dir) / report_name
        if evidence_dir.exists():
            shutil.rmtree(evidence_dir)
        evidence_dir.mkdir(parents=True)

        # Write evidence sections
        self._write_suricata_evidence(record, evidence_dir / "01_suricata_alert")
        self._write_network_context(record, evidence_dir / "02_network_context")
        self._write_forensic_evidence(record, evidence_dir / "03_local_forensic_analysis")
        self._write_virustotal_evidence(record, evidence_dir / "04_virustotal_analysis")
        self._write_ai_analysis(record, evidence_dir / "05_ai_analysis")
        self._write_actions_taken(record, evidence_dir / "06_actions_taken")
        self._write_system_config(record, evidence_dir / "07_system_configuration")

        # Generate README
        readme_content = self._generate_readme(record)
        (evidence_dir / "README.txt").write_text(readme_content, encoding="utf-8")

        # Generate timeline
        timeline_content = self._generate_chronology(record)
        (evidence_dir / "TIMELINE.txt").write_text(timeline_content, encoding="utf-8")

        # Generate metadata
        metadata = self._generate_metadata(record)
        (evidence_dir / "METADATA.json").write_text(
            json.dumps(metadata, indent=2, default=str, ensure_ascii=False),
            encoding="utf-8",
        )

        # Generate checksums
        checksums = self._generate_checksums(evidence_dir)
        (evidence_dir / "CHECKSUMS.sha256").write_text(checksums, encoding="utf-8")

        # Create ZIP
        zip_path = Path(self._temp_dir) / f"{report_name}.zip"
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for file_path in sorted(evidence_dir.rglob("*")):
                if file_path.is_file():
                    arcname = f"{report_name}/{file_path.relative_to(evidence_dir)}"
                    zf.write(file_path, arcname)

        # Cleanup temp directory
        shutil.rmtree(evidence_dir)

        logger.info("Generated forensic report: %s", zip_path)
        return zip_path

    def _write_json_file(self, data: Any, path: Path) -> None:
        """Write data as formatted JSON to a file.

        Args:
            data: Data to serialize.
            path: Output file path.
        """
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            json.dumps(data, indent=2, default=str, ensure_ascii=False),
            encoding="utf-8",
        )

    def _write_suricata_evidence(self, record: DecisionRecord, output_dir: Path) -> None:
        """Write Suricata alert evidence files.

        Args:
            record: The decision record.
            output_dir: Output directory.
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        self._write_json_file(
            record.alert.model_dump(mode="json"), output_dir / "original_alert.json"
        )

        sig_text = (
            f"Signature: {record.alert.alert_signature}\n"
            f"SID: {record.alert.alert_signature_id}\n"
            f"Category: {record.alert.alert_category}\n"
            f"Severity: {record.alert.alert_severity.value}\n"
        )
        (output_dir / "signature_details.txt").write_text(sig_text, encoding="utf-8")

    def _write_network_context(self, record: DecisionRecord, output_dir: Path) -> None:
        """Write network context evidence files.

        Args:
            record: The decision record.
            output_dir: Output directory.
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        if record.network_context:
            ctx = record.network_context.model_dump(mode="json")
            self._write_json_file(
                ctx.get("active_connections", []), output_dir / "active_connections.json"
            )
            self._write_json_file(ctx.get("dns_cache", []), output_dir / "dns_cache.json")
            self._write_json_file(ctx.get("arp_cache", []), output_dir / "arp_cache.json")
            if record.network_context.ip_reputation:
                self._write_json_file(
                    record.network_context.ip_reputation.model_dump(mode="json"),
                    output_dir / "ip_reputation.json",
                )
        else:
            (output_dir / "NOTE.txt").write_text(
                "Network context was not available for this alert.\n", encoding="utf-8"
            )

    def _write_forensic_evidence(self, record: DecisionRecord, output_dir: Path) -> None:
        """Write local forensic analysis evidence files.

        If include_suspect_files is enabled, copies actual suspect files
        into the archive (up to max_suspect_files_size total bytes).

        Args:
            record: The decision record.
            output_dir: Output directory.
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        if record.forensic_result:
            fr = record.forensic_result.model_dump(mode="json")
            self._write_json_file(
                fr.get("suspect_processes", []), output_dir / "suspect_processes.json"
            )
            self._write_json_file(fr.get("sysmon_events", []), output_dir / "sysmon_events.json")
            self._write_json_file(
                fr.get("registry_anomalies", []), output_dir / "registry_persistence.json"
            )
            self._write_json_file(
                fr.get("suspicious_files", []), output_dir / "suspicious_files.json"
            )
            self._write_json_file(
                fr.get("windows_events", []), output_dir / "windows_event_logs.json"
            )

            # Copy actual suspect files into the archive if enabled
            if self._include_suspect_files and record.forensic_result.suspicious_files:
                self._copy_suspect_files(record.forensic_result.suspicious_files, output_dir)
        else:
            (output_dir / "NOTE.txt").write_text(
                "Forensic analysis was not available for this alert.\n", encoding="utf-8"
            )

    def _copy_suspect_files(
        self,
        suspicious_files: list[dict[str, Any]],
        output_dir: Path,
    ) -> None:
        """Copy suspect files into the forensic evidence directory.

        Files are copied up to max_suspect_files_size total bytes.
        Each file is placed in a suspect_files/ subdirectory with its
        SHA-256 hash prepended to the filename to avoid collisions.

        Args:
            suspicious_files: List of file dicts with 'path' and 'size' keys.
            output_dir: Parent evidence output directory.
        """
        suspect_dir = output_dir / "suspect_files"
        suspect_dir.mkdir(parents=True, exist_ok=True)
        total_copied = 0
        copied_manifest: list[dict[str, str]] = []

        for file_info in suspicious_files:
            file_path_str = file_info.get("path")
            if not file_path_str:
                continue

            source = Path(file_path_str)
            if not source.exists() or not source.is_file():
                continue

            try:
                file_size = source.stat().st_size
            except OSError:
                continue

            # Enforce size budget (0 = no limit)
            if self._max_suspect_files_size > 0:
                if total_copied + file_size > self._max_suspect_files_size:
                    logger.info("Suspect file size budget exceeded, skipping remaining files")
                    break

            try:
                file_hash = self._compute_sha256(source)
                safe_name = f"{file_hash[:12]}_{source.name}"
                dest = suspect_dir / safe_name
                shutil.copy2(source, dest)
                total_copied += file_size
                copied_manifest.append(
                    {
                        "original_path": str(source),
                        "archive_name": safe_name,
                        "sha256": file_hash,
                        "size": str(file_size),
                    }
                )
            except (OSError, PermissionError) as exc:
                logger.warning("Failed to copy suspect file %s: %s", source, exc)

        # Write manifest of copied files
        if copied_manifest:
            self._write_json_file(copied_manifest, suspect_dir / "MANIFEST.json")
            logger.info(
                "Copied %d suspect files (%d bytes) into forensic report",
                len(copied_manifest),
                total_copied,
            )

    def _write_virustotal_evidence(self, record: DecisionRecord, output_dir: Path) -> None:
        """Write VirusTotal analysis evidence files.

        Args:
            record: The decision record.
            output_dir: Output directory.
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        if record.virustotal_results:
            results = [vt.model_dump(mode="json") for vt in record.virustotal_results]
            self._write_json_file(results, output_dir / "hash_results.json")
        else:
            (output_dir / "NOTE.txt").write_text(
                "No VirusTotal results available for this alert.\n", encoding="utf-8"
            )

    def _write_ai_analysis(self, record: DecisionRecord, output_dir: Path) -> None:
        """Write Claude AI analysis evidence files.

        Args:
            record: The decision record.
            output_dir: Output directory.
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        if record.analysis:
            self._write_json_file(
                record.analysis.model_dump(mode="json"), output_dir / "primary_analysis.json"
            )
        self._write_json_file(record.model_dump(mode="json"), output_dir / "final_decision.json")

    def _write_actions_taken(self, record: DecisionRecord, output_dir: Path) -> None:
        """Write response actions evidence files.

        Args:
            record: The decision record.
            output_dir: Output directory.
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        actions = [a.model_dump(mode="json") for a in record.actions_taken]
        self._write_json_file(actions, output_dir / "actions_log.json")

    def _write_system_config(self, record: DecisionRecord, output_dir: Path) -> None:
        """Write system configuration with sensitive data redacted.

        Args:
            record: The decision record.
            output_dir: Output directory.
        """
        output_dir.mkdir(parents=True, exist_ok=True)

        import platform
        import sys

        version_info = (
            f"OS: {platform.platform()}\n" f"Python: {sys.version}\n" f"WardSOAR: {self._version}\n"
        )
        (output_dir / "system_version.txt").write_text(version_info, encoding="utf-8")

    def _generate_readme(self, record: DecisionRecord) -> str:
        """Generate the human-readable README.txt content.

        Args:
            record: The decision record.

        Returns:
            Complete README text in English.
        """
        actions_text = ""
        for action in record.actions_taken:
            actions_text += f"  - {action.action_type.value}"
            if action.target_ip:
                actions_text += f" on {action.target_ip}"
            if action.executed_at:
                actions_text += f" at {action.executed_at.isoformat()}"
            actions_text += f" (success: {action.success})\n"

        analysis = record.analysis
        return README_TEMPLATE.format(
            generation_date=datetime.now(timezone.utc).isoformat(),
            version=self._version,
            record_id=record.record_id,
            alert_timestamp=record.alert.timestamp.isoformat(),
            src_ip=record.alert.src_ip,
            src_port=record.alert.src_port,
            dest_ip=record.alert.dest_ip,
            dest_port=record.alert.dest_port,
            protocol=record.alert.proto,
            signature=record.alert.alert_signature,
            signature_id=record.alert.alert_signature_id,
            category=record.alert.alert_category,
            severity=record.alert.alert_severity.value,
            verdict=analysis.verdict.value if analysis else "N/A",
            confidence=f"{analysis.confidence:.2f}" if analysis else "N/A",
            reasoning=analysis.reasoning if analysis else "N/A",
            actions_taken=actions_text or "  No actions taken.",
            contact=self._contact,
        )

    def _generate_chronology(self, record: DecisionRecord) -> str:
        """Generate a chronological timeline of the incident.

        Args:
            record: The decision record.

        Returns:
            Formatted timeline text.
        """
        entries: list[str] = []
        entries.append(
            f"{record.alert.timestamp.isoformat()}  Alert detected: "
            f"{record.alert.alert_signature} from {record.alert.src_ip}"
        )
        entries.append(f"{record.timestamp.isoformat()}  Pipeline processing started")

        if record.analysis:
            entries.append(
                f"{record.timestamp.isoformat()}  Analysis completed: "
                f"{record.analysis.verdict.value} (confidence: {record.analysis.confidence:.2f})"
            )

        for action in record.actions_taken:
            ts = action.executed_at.isoformat() if action.executed_at else "N/A"
            entries.append(
                f"{ts}  Action: {action.action_type.value} " f"(success: {action.success})"
            )

        return "INCIDENT TIMELINE\n" + "=" * 40 + "\n\n" + "\n".join(entries) + "\n"

    def _generate_metadata(self, record: DecisionRecord) -> dict[str, Any]:
        """Generate machine-readable metadata.

        Args:
            record: The decision record.

        Returns:
            Metadata dict.
        """
        return {
            "format_version": "1.0",
            "generator": f"WardSOAR v{self._version}",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "record_id": record.record_id,
            "alert_timestamp": record.alert.timestamp.isoformat(),
            "src_ip": record.alert.src_ip,
            "dest_ip": record.alert.dest_ip,
            "verdict": record.analysis.verdict.value if record.analysis else None,
            "confidence": record.analysis.confidence if record.analysis else None,
            "actions_count": len(record.actions_taken),
        }

    def _generate_checksums(self, directory: Path) -> str:
        """Compute SHA-256 checksums for all files in the evidence directory.

        Args:
            directory: Root directory of the evidence package.

        Returns:
            Content for CHECKSUMS.sha256 file.
        """
        lines: list[str] = []
        for file_path in sorted(directory.rglob("*")):
            if file_path.is_file() and file_path.name != "CHECKSUMS.sha256":
                rel_path = file_path.relative_to(directory)
                file_hash = self._compute_sha256(file_path)
                lines.append(f"{file_hash}  {rel_path}")
        return "\n".join(lines) + "\n"

    @staticmethod
    def _redact_config(config: dict[str, Any]) -> dict[str, Any]:
        """Remove sensitive values from a configuration dict.

        Replaces any value whose key contains 'key', 'secret',
        'password', or 'token' with '[REDACTED]'.

        Args:
            config: Raw configuration dict.

        Returns:
            Config dict with sensitive values replaced.
        """
        redacted: dict[str, Any] = {}
        for k, v in config.items():
            if isinstance(v, dict):
                redacted[k] = ForensicReportGenerator._redact_config(v)
            elif any(pattern in k.lower() for pattern in SENSITIVE_KEY_PATTERNS):
                redacted[k] = "[REDACTED]"
            else:
                redacted[k] = v
        return redacted

    @staticmethod
    def _compute_sha256(file_path: Path) -> str:
        """Compute SHA-256 hash of a file.

        Args:
            file_path: Path to the file.

        Returns:
            Hex-encoded SHA-256 hash.
        """
        sha256 = hashlib.sha256()
        with open(file_path, "rb") as f:
            for chunk in iter(lambda: f.read(8192), b""):
                sha256.update(chunk)
        return sha256.hexdigest()
